### ISSUE TITLE
Color theme change

### ISSUE THREAD

**Issue by 0xhealer** [articblush/vscode#1]
Hello,
I had downloaded the vsix file on my Windows machine and while installing the theme, it shows it as **Decay Theme** as shown below. Just wanted to clarify regarding that :)

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/76742567/183675729-889945b2-a88e-4f49-8abd-960cbbee6e44.png">

**Comment by meyzatech** [comment]
Greetings, dear friend This is a minor technical error, and since Articblush and Decay share practically the same maintainers and developers, it's possible that it was posted here by accident. Please try the other method rather than the vsix approach; the problem will be rectified in a few weeks , Thank You!
